package handler

import (
	"strconv"
  "net/http"
  "github.com/gin-gonic/gin"
	"github.com/slaghuis/YC-Product/pkg/models"
)

type CreateSKURequest struct {
    OptionIDs []uint  `json:"option_ids"`
    Price     float64 `json:"price"`
    Stock     int     `json:"stock"`
}

func (h *Handler) CreateSKUHandler(c *gin.Context) {
	token := c.GetString("token_key")
	id := c.Param("id")

	var req struct {
		OptionIDs []uint  `json:"option_ids" binding:"required"`
    Price     float64 `json:"price" binding:"required"`
    Stock     int     `json:"stock"`
  }
  if err := c.ShouldBindJSON(&req); err != nil {
      c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
      return
  }

	sku, err := h.SkuService.CreateSKU(c, id, req.OptionIDs, req.Price, req.Stock, token)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

  c.JSON(http.StatusCreated, sku)
}

type CreateAllSKURequest struct {
    Price     float64 `json:"price"`
    Stock     int     `json:"stock"`
}

func (h *Handler) CreateAllSKUsHandler(c *gin.Context) {
  var req CreateAllSKURequest
  if err := c.ShouldBindJSON(&req); err != nil {
      c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
      return
  }

  productID, _ := strconv.Atoi(c.Param("id"))
  var product models.Product
  if err := h.db.First(&product, productID).Error; err != nil {
      c.JSON(http.StatusNotFound, gin.H{"error": "Product not found"})
      return
  }
  skus, err := models.GenerateAllSKUs(h.db, product, req.Price, req.Stock)
  if err != nil {
      c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
      return
  }

  c.JSON(http.StatusCreated, skus)
}

// auth.GET("/:id/skus", h.GetProductSKUHandler)

func (h *Handler) GetProductSKUHandler(c *gin.Context) {
  id := c.Param("id")
	token := c.GetString("token_key")

	skuList, err := h.SkuService.GetProductSKUList(c, id, token)
  if err != nil {
    c.JSON(http.StatusNotFound, gin.H{"error": "skus not found"})
    return
  }

  c.JSON(http.StatusOK, skuList)
}

func (h *Handler) GetSKUHandler(c *gin.Context) {
	id := c.Param("id")
	token := c.GetString("token_key")

	item, err := h.SkuService.GetSKU(c, id, token)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

  c.JSON(http.StatusOK, gin.H{
    "id":         item.ID,
    "code":       item.Code,
    "price":      item.Price,
    "stock":      item.Stock,
  })
}

// Respond to auth.PUT("/skus/:id", h.UpdateSKUHandler)
/* type UpdateSkuRequestBody struct {
  Code   string   `json:"code"`
  Price  float64  `json:"price"`
  Stock  int      `json:"stock"`
}
*/
func (h *Handler) UpdateSKUHandler(c *gin.Context) {
	token := c.GetString("token_key")
	id := c.Param("id")   // SKU.id

	var req struct {
		Code   string   `json:"code"`
	  Price  float64  `json:"price"`
	  Stock  int      `json:"stock"`
  }
  if err := c.ShouldBindJSON(&req); err != nil {
      c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
      return
  }

	// Code is empty, or might be empty
	// h.LogJson(req)

	sku, err := h.SkuService.UpdateSKU(c, id, req.Price, req.Stock, token)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

  c.JSON(http.StatusOK, sku)
}

/*
func (h *Handler) UpdateSKUHandler(c *gin.Context) {
  id := c.Param("id")   //SKU.id

  body := UpdateSkuRequestBody{}

  if err := c.BindJSON(&body); err != nil {
      c.AbortWithError(http.StatusBadRequest, err)
      return
  }

  var item models.SKU

  if result := h.db.First(&item, id); result.Error != nil {
      c.AbortWithError(http.StatusNotFound, result.Error)
      return
  }

//  item.Code = body.Code  // Hold back on this, let me first see the autogenerated number
  item.Price = body.Price
  item.Stock = body.Stock
  // item.BarCode = body.BarCode  // I need to add this sometime

  h.db.Save(&item)

  c.JSON(http.StatusOK, &item)
}
*/

// Handle auth.DELETE("/skus/:id", h.DeleteSKUHandler)
func (h *Handler) DeleteSKUHandler(c *gin.Context) {
  id := c.Param("id")

  if result := h.db.Delete(&models.SKU{}, id); result.Error != nil {
      c.AbortWithError(http.StatusInternalServerError, result.Error)
      return
  }

  c.JSON(http.StatusOK, gin.H{
    "status": "success",
    "message": "SKU successfully deleted",
  })
}

// Respond to auth.GET("/skus/:id", h.UpdateSKUHandler)
type SKUOptions struct {
  Options	[]uint  `json:"options"`     // selectedOptionIDs = []uint{optionIDForSmall, optionIDForRed}
}

func (h *Handler) GetSKUfromProductOptions(c *gin.Context) {
	id := c.Param("id")
	productID, err := h.StrToUint(id)
  if err != nil {
    c.JSON(http.StatusBadRequest, gin.H{
      "status": "error",
      "message": "failed to parse product id: " + err.Error(),
    })
    return
  }

	// selectedOptionIDs = []uint{optionIDForSmall, optionIDForRed}
	var req SKUOptions
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{
      "status": "error",
      "message": "failed to parse options list: " + err.Error(),
    })
		return
	}

	// h.LogJson(req)

	var sku models.SKU
	err = h.db.
    	Preload("Options").
    	Joins("JOIN sku_options ON sku_options.sk_uid = skus.id").
    	Where("skus.product_id = ?", productID).
    	Where("sku_options.option_id IN ?", req.Options).
    	Group("skus.id").
    	Having("COUNT(sku_options.option_id) = ?", len(req.Options)).
    	First(&sku).Error

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{
      "status": "error",
      "message": "SKU not found: " + err.Error(),
    })
		return
	}
	c.JSON(http.StatusOK, &sku)
}
